# Generated by Django 4.1.7 on 2023-04-18 14:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchantRequestID', models.CharField(max_length=255)),
                ('checkoutRequestID', models.CharField(max_length=255)),
                ('resultCode', models.IntegerField()),
                ('resultDesc', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('mpesaReceiptNumber', models.CharField(max_length=255)),
                ('transactionDate', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255, unique=True)),
                ('expiry', models.DateTimeField(default=datetime.datetime(2023, 4, 18, 18, 36, 51, 801039))),
            ],
        ),
        migrations.CreateModel(
            name='PendingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reason', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('phone_number', models.CharField(max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
