# Generated by Django 4.1.7 on 2023-04-18 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_daraja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=255)),
                ('TransID', models.CharField(max_length=255)),
                ('TransTime', models.CharField(max_length=255)),
                ('TransAmount', models.CharField(max_length=255)),
                ('BusinessShortCode', models.CharField(max_length=255)),
                ('BillRefNumber', models.CharField(max_length=255)),
                ('InvoiceNumber', models.CharField(max_length=255)),
                ('OrgAccountBalance', models.CharField(max_length=255)),
                ('ThirdPartyTransID', models.CharField(max_length=255)),
                ('MSISDN', models.CharField(max_length=255)),
                ('FirstName', models.CharField(max_length=255)),
                ('MiddleName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='token',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 20, 24, 21, 535397)),
        ),
    ]
